language: ruby

rvm:
  - 2.0.0

gemfile:
  - Gemfile

script:
  - bundle exec rake 
  
deploy:
  provider: heroku
  api_key:
    secure: Z/ktPbh8eB5P9x0ayHcVoHtXXO749Fl2stHTIlMx3orcaio7jlLkxaezKvRS/JOCtCA7Ija7UNOKQ+Ao06Vg0M9+NBMLvYlhDE1RP6SYjeRpM6XJQkpBfQiMfRdzwjzh3RKaM79OQBfXLA0bt0grSWEtcOCq7n6Ew7imMCljX7M=
  app:
    staging: pjsearch-staging
