# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6535566f906b40e71a960435b740cc67526aa672b6238757b1a5b35f7e5b60d35e3c9c9d2507d92ba76e1a3c3bea4e8084695bf4220b63d88f32f45a561c6ec5

test:
  secret_key_base: ff7c436a66ba16faecad5e193f1901e37ba92aacc90223207c0ee969169b8fca3b3f9cad5544ff6d546e1c1690c0ce46939fb04877a8f22f37e137f8cfcff5f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
